### ISSUE TITLE
Multifox auto-redirecting on specific sites

### ISSUE THREAD

**Issue by orange-tsai** [hultmann/multifox#211] opened 2015-05-07 14:34 UTC
My Multifox (on auto-update) is automatically redirecting to a different version of the same website. (crowdfireapp.com). Tried deleting history, cache, cookies and restarting. Site works everywhere else correctly, and it does work when I turn off Multifox.

**Comment by hultmann** [comment] 2015-05-12 04:08
I'm not able to reproduce this. 
crowdfireapp.com redirects to http://www.crowdfireapp.com/ using profile 1 or 2.

**Comment by orange-tsai** [comment] 2015-05-12 19:33
I'm updating to firefox 38.0, it's an issue still for me with no add-ons besides multi-fox. I'm on a mac, I can shoot a video if you'd like?

**Comment by orange-tsai** [comment] 2015-05-12 20:07
I've just tried a fresh install and it's still doing it. (FF install) so it's not multi fox, it has to be bigger than that. Do you have any ideas?

**Comment by hultmann** [comment] 2015-05-16 20:54
Did you try inspecting network requests/responses? It is probably a server issue.

(Closing since it is not a Multifox bug)

**Closed as completed by hultmann** 2015-05-16 20:54 UTC
