### ISSUE TITLE
Hybrid between tab and window mode.

### ISSUE THREAD

**Issue by leonardoarroyo** [hultmann/multifox#199] opened 2015-02-25 12:45 UTC
Hello! I've just started using multifox and when I was quite displeased to see there's no hybrid between window and tab mode. One very big annoiance is the fact that new tabs default to the default profile. I think implementing something as (Open new tabs with default profile/Open new tabs with current tab profile).

This would quickly allow someone using the later method to leverage the power of per-tab profiles aswell as windows profiles(which are nothing more than tab mode with tabs opening with the specified profile) at the same time without losing any functionality.

Are there any techinical challenges to implement such feature?

**Comment by hultmann** [comment] 2015-03-15 22:22
A workaround: open about:config and change browser.newtab.url to something different than about:newtab (e.g. about:blank), Multifox will fail to detect new tabs and it will keep the identity (it's actually a bug I may fix eventually).

(the technical challenge is actually detecting new tab)

**Comment by hultmann** [comment] 2015-03-15 22:43
dupe of #194?

**Closed as completed by hultmann** 2015-03-15 22:43 UTC
