### ISSUE TITLE
IP addresses won't work with Multifox 2

### ISSUE THREAD

**Issue by tbs** [hultmann/multifox#6] opened 2011-05-04 23:02 UTC
I got this error on Firefox console:

Error: [Exception... "Component returned failure code: 0x804b0050 (NS_ERROR_INSUFFICIENT_DOMAIN_LEVELS) [nsIEffectiveTLDService.getBaseDomainFromHost]"  nsresult: "0x804b0050 (NS_ERROR_INSUFFICIENT_DOMAIN_LEVELS)"  location: "JS frame :: resource://multifox-modules/main.js :: getTldFromHost :: line 3639"  data: no]
Source File: resource://multifox-modules/main.js
Line: 3639

Gmail loading forever, fail to load embed Youtube videos in pages and more problems..

**Comment by hultmann** [comment] 2011-05-05 01:12
Are you using Multifox 2.0b2?

**Comment by tbs** [comment] 2011-05-05 02:31
Yes, Multifox 2.0b2.

**Comment by hultmann** [comment] 2011-05-05 03:17
Probably it is caused by connections using IP addresses instead of host names (http://192.168.1.1/). This will be fixed in the next beta.

However, Gmail and videos work fine for me.

**Comment by tbs** [comment] 2011-05-05 12:00
Some more error message, maybe helpful for you:

Error: [Exception... "Component returned failure code: 0x804b0051 (NS_ERROR_HOST_IS_IP_ADDRESS) [nsIEffectiveTLDService.getBaseDomainFromHost]"  nsresult: "0x804b0051 (NS_ERROR_HOST_IS_IP_ADDRESS)"  location: "JS frame :: resource://multifox-modules/main.js :: getTldFromHost :: line 3639"  data: no]
Source File: resource://multifox-modules/main.js
Line: 1153

---

Error: Error: console.assert - documentCookieGetter not logged=nullnull,http://www.youtube.com/embed/cJNpyIIlJ3w - false
Source File: resource://multifox-modules/new-window.js
Line: 192

---

Error: uncaught exception: Error: Multifox (BETA) - Return value not received.
http://www.youtube.com/embed/cJNpyIIlJ3w
{"from":"cookie","cmd":"get"}

---

Error message from this page http://www.guru3d.com/news/transformers-3-dark-of-the-moon-official-trailer/

**Comment by hultmann** [comment] 2011-05-05 22:52
Thanks for the link, errors are caused by connections to http://194.71.11.69/pub/games/PC/guru3d/img-cache/fancybox/jquery.fancybox-1.3.1.css

**Comment by hultmann** [comment] 2011-08-01 05:59
This was fixed in 2.0b3. Please let me know if there is still an issue.

**Closed as completed by hultmann** 2011-08-01 05:59 UTC
