### ISSUE TITLE
LocalStorage is not shared between tabs

### ISSUE THREAD

**Issue by jlamberg** [hultmann/multifox#204] opened 2015-04-07 07:46 UTC
I noticed that Multifox does not share LocalStorage between tabs and profiles, which is wrong, IMO. Firefox does share the storage between windows and tabs, by default, so the error is most likely in this add-on. Also, Google Chrome's Multilogin plugin shares it between profiles and windows.

I made a test to display how it works currently, and the same test can be used when this issue has been fixed, of course:

http://jsfiddle.net/sr0xrvkj/

How to reproduce:
1. Create two new profiles.
2. Open a new tab, select profile 1 and load the jsfiddle page.
3. Select an option in the drop-down menu and refresh the page. (The option selected before page refresh is selected, again, so LocalStorage works as expected.)
4. Open a new tab, select profile 2 and load the jsfiddle page.

Observed result:

The drop-down has its first option selected, by default, meaning that Multifox does not share the LocalStorage value set with profile 1 in step 3.

Expected result:

The drop-down has the same value selected as was after step 3, i.e. LocalStorage is shared between profiles.

I am using Multifox 3.1.0 and Firefox 36.0.1.

**Comment by hultmann** [comment] 2015-04-07 16:28
It is not a bug at all, it is the expected result.

Why do you think localStorage should be shared between profiles? It is like saying "cookies should be shared between profiles".

**Comment by hposca** [comment] 2015-04-07 17:42
IMHO, this bug (as jlamberg says) is exactly what makes multifox wonderful!
The purpose of multifox is to make the profiles really independent from one another! With this we can open many e-mail accounts and access the same site as different users using firefox!

**Comment by kofalt** [comment] 2015-04-07 17:59
Agreed with above, confused how this could be considered anything but intended behaviour.

Contaminating state between profiles would break the exact reason this addon exists?

**Comment by jlamberg** [comment] 2015-04-07 20:32
@hultmann, my assumption to share localStorage came from reading the Web Storage specification from W3C, for example. Currently, its latest version can be found at http://www.w3.org/TR/2013/REC-webstorage-20130730/.

IMO, both sections 1 and 4.3 of the spec address my concerns quite clearly:

> The second storage mechanism is designed for storage that spans multiple windows, and lasts beyond the current session. In particular, Web applications may wish to store megabytes of user data, such as entire user-authored documents or a user's mailbox, on the client side for performance reasons. ... Each site has its own separate storage area.

and, respectively:

> The localStorage object provides a Storage object for an origin.
> User agents must have a set of local storage areas, one for each origin.

Mozilla's implementation of the spec doesn't seem to deviate from it if I understand the following in https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#Web_Storage_concepts_and_usage correctly:

> The two mechanisms within Web Storage are as follows:
> -    sessionStorage maintains a separate storage area for each given origin that's available for the duration of the page session (as long as the browser is open, including page reloads and restores)
> -    localStorage does the same thing, but persists even when the browser is closed and reopened.

I don't see cookies and localStorage as equivalents related to this issue because cookies have a much more fine-grained storage model, for example, but I could be wrong.

@hposca, for logging in to a site with different user accounts in different profiles/tabs/windows, not sharing cookies would be enough, and that is what caught my attention of Multifox in the first place. 

My specific use case for Multifox is to have 2-4 users access the same site from one public computer with all of them being logged in simultaneously, and having them share localStorage would make many things a lot easier.

I see lots of uses for Multifox even when localStorage is shared. If you are against that, maybe give us users the option to have it shared, anyway, so that we can use the add-on in ways you might not have thought before? :)

**Comment by kofalt** [comment] 2015-04-08 01:57
> My specific use case for Multifox is to have 2-4 users access the same site from one public computer with all of them being logged in simultaneously

Are you aware that Firefox has a profile manager? It supports a variety of useful things, including running multiple at once (each in its own window). If I read you correctly that might be exactly what you need!

> having them share localStorage would make many things a lot easier

Can you give a specific example?

**Comment by jlamberg** [comment] 2015-04-08 08:55
> Are you aware that Firefox has a profile manager? It supports a variety of useful things, including running multiple at once (each in its own window). If I read you correctly that might be exactly what you need!

Yes, I am aware of it but AFAIK, it only allows one profile to be active at a time, which doesn't help me.

My case is about having a small team of sales reps (2-4 people) in one location where they share a computer and need to be logged in simultaneously; the hassle of logging one person out and another back in is too slow and distracting. 

Usually, the reps arrive one after another, and the first person at a location will do a couple of selections that the others will use, too. Others can change the selected options for themselves but by default they need to be the same. Sometimes, the selected options from the previous day are used as a default as well. LocalStorage is perfect for that while Multifox is perfect for keeping all reps logged in to the same site/application. 

We've thought about storing the selected options in the database, too, but it's much more work especially when the options are not needed in the backend in that way. Using localStorage is by far the easiest way to get things working for us and works perfectly if the reps log out and back in without Multifox but that is not feasible, as I previously mentioned.

My life would be a lot easier if had I the best of both, i.e. to have the reps share the localStorage while all being logged in at the same time using Multifox.

**Comment by hultmann** [comment] 2015-04-13 22:05
I'm WONTFIXing this issue, but if you want to disable localStorage, just locate the following line (main.js):

`Object.defineProperty(window, "localStorage", {`

and change localStorage to something else, like "zzz"

**Closed as completed by hultmann** 2015-04-13 22:05 UTC
