### ISSUE TITLE
Multifox 2.0b8 (BETA) interferes with the new google login

### ISSUE THREAD

**Issue by fsparv** [hultmann/multifox#124] opened 2013-11-04 21:09 UTC
I've discovered that when google logs me out I need to delete the multifox profile for that google account before I can log in again. Previously this wasn't a problem. The BETA version with the auto detection of profiles is awesome most of the time but every now an then it causes confusion. Combined with tab groups it makes switching work contexts a breeze (company/client1/client2/etc/personal). :) Please keep enhancing it!

**Comment by GJRobert** [comment] 2013-11-06 04:14
It's really annoying every time Google mess things up and break Multifox Beta. Now I cannot log in to Google+ (other Google services seem to work).

Multifox BETA is really the essential extension :) Thanks for your great work!

**Comment by hultmann** [comment] 2013-11-07 17:00
Actually, I believe I have this fixed. More details in a few days.

**Comment by MurzNN** [comment] 2013-11-22 07:09
Can you describe more how to fix this problem? I expiring this problem before and today too, and I didn't see any updated versions in http://br.mozdev.org/multifox/all.html 
Maybe we need to use current Multifox 2.0b8 and update some settings, or clear cookies?

**Comment by hultmann** [comment] 2013-12-09 06:47
Sorry for the delay, I'll be working on it over this week.

**Comment by MurzNN** [comment] 2013-12-09 07:47
I have found the way how to solve problem with google re-login (google re-ask password for current login on page, and after you typing password and press Submit - nothing happened) in current version:
1. Select in Multifox menu "Add account".
2. Enter your login and password.

**Comment by hultmann** [comment] 2013-12-11 22:03
Please try:
http://code.google.com/p/multifox/downloads/detail?name=all-accounts-2.1a1pre.xpi&can=2&q=#makechanges

P.S. AllAccounts is the new name I'm using for now.

**Comment by mpkossen** [comment] 2013-12-12 05:34
Thanks, looks good! This is what I was looking for!

**Comment by MurzNN** [comment] 2013-12-13 12:33
Thanks, seems problem is fixed in new module. Good that new name is different with Multifox classic, because old users don't understand what is the differnce.

P.S. Good alternative name may be "All My Circuits" (c) Futurama :-)

**Comment by hultmann** [comment] 2013-12-14 23:00
All My Accounts? :-) I'm considering it

Closing as all issues seem to be fixed.

**Closed as completed by hultmann** 2013-12-14 23:00 UTC

**Comment by fsparv** [comment] 2013-12-24 20:56
Unfortunately this appears to break login to workflow max. Since this is my time tracking system, it's a complete show stopper for me :( :( :-1: Do you want a separate ticket made on the google code site - (why are you using google code? Google code hurts my eyes :( )

**Comment by fsparv** [comment] 2013-12-24 20:57
oops, links would probably help.... https://my.workflowmax.com/login.aspx?ReturnUrl=%2fdefault.aspx

**Comment by fsparv** [comment] 2013-12-25 16:08
And I now seem to get this in Jira most if not all of the time when submitting forms...

JIRA could not complete this action due to a missing form token.

You may have cleared your browser cookies, which could have resulted in the expiry of your current form token. A new form token has been reissued.

Request URL: /secure/WorkflowUIDispatcher.jspa

The original input has been captured and you can retry the operation.

Sorry, but any file attachments in the original input will be lost.

**Comment by hultmann** [comment] 2013-12-27 00:52
@fsparv Are these regressions from 2.0b8? Please file them at https://github.com/hultmann/allmyaccounts/issues

**Comment by fsparv** [comment] 2013-12-28 17:55
Yes regressions, (or something changed concurrently on those sites). I also had a problem with fidelity net benefits yesterday as well... I could log-in ok but the some, but not all of the internal links broght me to a login page. I'll enter this stuff over there.
